<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="SARAVANAN-PC" name="Dummy" tests="1" failures="0" timestamp="19 Sep 2017 06:47:00 GMT" time="8.391" errors="1">
  <testcase name="Test" time="8.391" classname="Dummy">
    <error type="org.openqa.selenium.WebDriverException" message="Reached error page: about:neterror?e=nssFailure2&amp;u=https%3A//pubads.g.doubleclick.net/gampad/ads%3Fsz%3D970x250%26gdfp_req%3D1%26ad_rule%3D0%26iu%3D/4061/com.ythome%26impl%3Difr%26scp%3Dmpvid%253DIFtQGtgoyAwR8WCX%2526ssl%253D1%2526ytexp%253D9487552%2C23703362%2C23700579%2C9422596%2C9483894%2C23703094%2C9471239%2C9467242%2C9479479%2C9477358%2C9453586%2C9488276%2C9487926%2C23702263%2C9457114%2C23701917%2C23701914%2526ytdevice%253D1%2526klg%253Den%2526kbsg%253DHPIN170919%2526kmyd%253Dad_creative_1%2526kga%253D-1%2526kgg%253D-1%2526dc_yt%253D1%2526vrex%253D10%2C20%26d_imp%3D1%26ytdevice%3D1%26pucrd%3DCgYIABAAGAA%26correlator%3D7903228872086139&amp;c=UTF-8&amp;f=regular&amp;d=An%20error%20occurred%20during%20a%20connection%20to%20pubads.g.doubleclick.net.%0A%0APeer%20reports%20it%20experienced%20an%20internal%20error.%0A%0AError%20code%3A%20%3Ca%20id%3D%22errorCode%22%20title%3D%22SSL_ERROR_INTERNAL_ERROR_ALERT%22%3ESSL_ERROR_INTERNAL_ERROR_ALERT%3C/a%3E%0A
Build info: version: &#039;3.5.3&#039;, revision: &#039;a88d25fe6b&#039;, time: &#039;2017-08-29T12:54:15.039Z&#039;
System info: host: &#039;SARAVANAN-PC&#039;, ip: &#039;172.16.4.235&#039;, os.name: &#039;Windows 7&#039;, os.arch: &#039;x86&#039;, os.version: &#039;6.1&#039;, java.version: &#039;1.8.0_131&#039;
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{moz:profile=C:\Users\SARAVA~1\AppData\Local\Temp\rust_mozprofile.Mg65WgiZnWzT, rotatable=false, timeouts={implicit=0, pageLoad=300000, script=30000}, pageLoadStrategy=normal, platform=XP, specificationLevel=0, moz:accessibilityChecks=false, acceptInsecureCerts=false, browserVersion=55.0.3, platformVersion=6.1, moz:processID=8780, browserName=firefox, javascriptEnabled=true, platformName=XP}]
Session ID: 4781d056-2689-4449-8484-a8dd1440e4d8">
      <![CDATA[org.openqa.selenium.WebDriverException: Reached error page: about:neterror?e=nssFailure2&u=https%3A//pubads.g.doubleclick.net/gampad/ads%3Fsz%3D970x250%26gdfp_req%3D1%26ad_rule%3D0%26iu%3D/4061/com.ythome%26impl%3Difr%26scp%3Dmpvid%253DIFtQGtgoyAwR8WCX%2526ssl%253D1%2526ytexp%253D9487552%2C23703362%2C23700579%2C9422596%2C9483894%2C23703094%2C9471239%2C9467242%2C9479479%2C9477358%2C9453586%2C9488276%2C9487926%2C23702263%2C9457114%2C23701917%2C23701914%2526ytdevice%253D1%2526klg%253Den%2526kbsg%253DHPIN170919%2526kmyd%253Dad_creative_1%2526kga%253D-1%2526kgg%253D-1%2526dc_yt%253D1%2526vrex%253D10%2C20%26d_imp%3D1%26ytdevice%3D1%26pucrd%3DCgYIABAAGAA%26correlator%3D7903228872086139&c=UTF-8&f=regular&d=An%20error%20occurred%20during%20a%20connection%20to%20pubads.g.doubleclick.net.%0A%0APeer%20reports%20it%20experienced%20an%20internal%20error.%0A%0AError%20code%3A%20%3Ca%20id%3D%22errorCode%22%20title%3D%22SSL_ERROR_INTERNAL_ERROR_ALERT%22%3ESSL_ERROR_INTERNAL_ERROR_ALERT%3C/a%3E%0A
Build info: version: '3.5.3', revision: 'a88d25fe6b', time: '2017-08-29T12:54:15.039Z'
System info: host: 'SARAVANAN-PC', ip: '172.16.4.235', os.name: 'Windows 7', os.arch: 'x86', os.version: '6.1', java.version: '1.8.0_131'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{moz:profile=C:\Users\SARAVA~1\AppData\Local\Temp\rust_mozprofile.Mg65WgiZnWzT, rotatable=false, timeouts={implicit=0, pageLoad=300000, script=30000}, pageLoadStrategy=normal, platform=XP, specificationLevel=0, moz:accessibilityChecks=false, acceptInsecureCerts=false, browserVersion=55.0.3, platformVersion=6.1, moz:processID=8780, browserName=firefox, javascriptEnabled=true, platformName=XP}]
Session ID: 4781d056-2689-4449-8484-a8dd1440e4d8
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:185)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:120)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:164)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:82)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:646)
	at org.openqa.selenium.remote.RemoteWebDriver.get(RemoteWebDriver.java:370)
	at Dummy.Test(Dummy.java:43)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:669)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:877)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1201)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:776)
	at org.testng.TestRunner.run(TestRunner.java:634)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:425)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:420)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:385)
	at org.testng.SuiteRunner.run(SuiteRunner.java:334)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1318)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1243)
	at org.testng.TestNG.runSuites(TestNG.java:1161)
	at org.testng.TestNG.run(TestNG.java:1129)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- Test -->
</testsuite> <!-- Dummy -->
